set -n console log=log.txt
set console debug=debug.txt
set cpu idle
set cpu autotime=on

;
; Initializing the magnetic drums.
;
attach -e drum0 ~/Yandex.Disk/simh/BESM6/MB/drum1x.bin
attach -e drum1 ~/Yandex.Disk/simh/BESM6/MB/drum2x.bin

;
; Initializing a scratch disk.
;
attach -n md06 ~/Yandex.Disk/simh/BESM6/MD/2052

;
; Attaching system disk.
;
attach -e md07 ~/Yandex.Disk/simh/BESM6/MD/2253

;
; Attaching an output file.
;
attach -n prn0 output.txt

;
; Telnet socket for all terminals
;
attach tty 4199

;
; Line 1: Main teletype (operator console)
;
attach tty1 console
set tty1 vt
set tty1 authbs

;
; Line 17: DKS test terminal
;
set tty17 vt
set tty17 dks
set tty17 authbs

;
; Enable TTY debugging
;
set tty debug

echo ###
echo ### Booting OS DISPAK...
echo ###

;
; Booting OS DISPAK.
;
load boot_dispak.b6
run 2000
go
