set -n console log=log.txt
set console debug=debug.txt
set console wru=7
set autotime=on
set throttle=1m
;set cpu idle - лезет мусор на термиал
;set cpu debug
;set mmu debug
;set drum debug
;set disk debug


;
; Initializing the magnetic drums.
;
attach -e drum0 ~/Yandex.Disk/simh/BESM6/MB/drum1x.bin
attach -e drum1 ~/Yandex.Disk/simh/BESM6/MB/drum2x.bin

;
; Initializing a scratch disk.
;
attach -n md06 ~/Yandex.Disk/simh/BESM6/MD/2052

;
; Attaching system disks.
;
set md1 ec-5061
set md4 ec-5061
;attach -e md00 ~/Yandex.Disk/simh/BESM6/MD/2453
attach -e md01 ~/Yandex.Disk/simh/BESM6/MD/2148
attach -r md02 ~/Yandex.Disk/simh/BESM6/MD/2248
;attach -r md03 ~/Yandex.Disk/simh/BESM6/MD/4023
attach -e md04 ~/Yandex.Disk/simh/BESM6/MD/2095
attach -e md05 ~/Yandex.Disk/simh/BESM6/MD/2063
attach -e md07 ~/Yandex.Disk/simh/BESM6/MD/2253
;attach -e md07 ~/Yandex.Disk/simh/BESM6/MD/EC5061/2353
;attach -e md10 ~/Yandex.Disk/simh/BESM6/MD/2100
;attach -e md11 ~/Yandex.Disk/simh/BESM6/MD/EC5061/2353
attach -e md40 ~/Yandex.Disk/simh/BESM6/MD/EC5061/2061
attach -e md41 ~/Yandex.Disk/simh/BESM6/MD/EC5061/2070
attach -e md42 ~/Yandex.Disk/simh/BESM6/MD/EC5061/2094
attach -e md43 ~/Yandex.Disk/simh/BESM6/MD/EC5061/2086
attach -e md44 ~/Yandex.Disk/simh/BESM6/MD/RAK/2073
attach -e md45  ~/Yandex.Disk/simh/BESM6/MD/EC5061/2348
;attach -r md46 ~/Yandex.Disk/simh/BESM6/MD/EC5061/2095
;attach -r md47 ~/Yandex.Disk/simh/BESM6/MD/EC5061/
attach -r mg50 ~/Yandex.Disk/simh/BESM6/ML/209
attach -r mg51 ~/Yandex.Disk/simh/BESM6/ML/211
attach -r mg52 ~/Yandex.Disk/simh/BESM6/ML/212
attach -r mg53 ~/Yandex.Disk/simh/BESM6/ML/213
attach -r mg54 ~/Yandex.Disk/simh/BESM6/ML/214
attach -e mg55 ~/Yandex.Disk/simh/BESM6/ML/202
attach -e mg56 ~/Yandex.Disk/simh/BESM6/ML/203
attach -e mg57 ~/Yandex.Disk/simh/BESM6/ML/204
attach -r mg61 ~/Yandex.Disk/simh/BESM6/ML/206
attach -r mg62 ~/Yandex.Disk/simh/BESM6/ML/207
attach -r mg63 ~/Yandex.Disk/simh/BESM6/ML/208
attach -r mg64 ~/Yandex.Disk/simh/BESM6/ML/210
;
; Attaching an output file.
;
;attach -n prn0 ~/Yandex.Disk/simh/BESM6/ACPU/output.txt
attach -n prn1 ~/Yandex.Disk/simh/BESM6/ACPU/output1.txt
attach -n vu0 ~/Yandex.Disk/simh/BESM6/UVU/punchcard.txt
attach -n pi0 ~/Yandex.Disk/simh/BESM6/UVU/punchcard1.txt
attach -n pl0 ~/Yandex.Disk/simh/BESM6/UVU/punch.txt

;
; Allowing telnet connections, port 4199.
;
;attach tty 4199
attach tty1 4202
;attach tty2 4203
attach tty11 4203
set tty11 dks
;
; Attaching a terminal serving as the operator console.
;
; This works on UNIX-like systems.
attach tty1 console 
; On Windows, a UTF-8 connnection works better over telnet.
; Use a different port for the operator console just in case.
;attach tty Line=1,4198
;set env PATH %PATH%;C:\Program Files (x86)\PuTTY
;! start putty telnet://localhost:4198
;
; On Unix, telnet can also be used for the operator console.
;! gnome-terminal -x sh -c "telnet Localhost 4198" &
;
; Terminal modes (how to enter Cyrillics, should the backspace be erasing), etc.
; (authbs == authentic non-erasing)
;
; Using UTF-8 for input
; set tty1 unicode,authbs
;
; Entering Russian letters as lowercase Latin letters
; according to the standard Russian layout
;set tty1 jcuken,authbs
;
; Entering Russian letters as corresponding lowercase Latin letters.
; Q = "ya", W = "ve", Y = "yeru", J = "short I", X = "soft sign",
; C = "ts", V = "zhe", grave = "yu", tilde = "ch", { = "sh", } = "shch",
; | = "reverse e"
set tty1 authbs
;set -n tty1 log=tty1.txt
set tty2 authbs
set tty3 authbs
set tty4 authbs
set tty5 authbs
set tty6 
set tty7 
set tty8 
set tty9 
set tty10 
set tty11 
set tty12 
set tty13 
set tty14 
set tty15 
set tty16 
set tty17 
set tty18 
set tty19 
set tty20 
set tty21 
set tty22 
set tty23 
set tty24 

;
; Enabling the true LRU behavior of caches
; slows down the simulation speed ~20%
;
;set mmu cache

echo ###
echo ### Zeroing out the first page of RAM (as would be entered from
echo ### switch registers after powering up the machine,
echo ### likely about once a year or less).
echo ###

d -ml 1 xta, vtm 1777(1)
d -ml 2 atx (1), utm -1(1)
d -ml 3 v1m 2(1), stop
run 1

echo ### 
echo ### Done; data cache registers are displayed above. An error message
echo ### would be usually displayed there after a STOP instruction.
echo ### Naturally, at the moment they all contain zeros. Booting the OS now...
echo ###
;
; Booting OS DISPAK.
;
load ~/Yandex.Disk/simh/BESM6/OSZAGR/boot_dispak.b6
run 2000
;quit
