# Attaching the input device
at  vu0 input3.txt
# Waiting for the end of initial setup
# Now we're ready to send commands from the front panel
echo Requesting input from the punch tape reader (FS8), it takes a few seconds
d 6 1
d 5 10
set cpu req
expect -r "В0.*\n"
go
